### ISSUE TITLE
Using sets does not work

### ISSUE THREAD

**Issue by gazialankus** [google/serialization.dart#11]
I'm using the transformers with `import '..._serialization_rules.dart'`. I'm not supplying a format field to the Serialization constructor to use the default. 

`List`s and `Map`s are serialized just fine. `Set`s aren't. I get the below stacktrace when trying to serialize an object that has a `Set`. 

```
Exception: Uncaught Error: Unsupported operation: Attempted to serialize type without a defined rule {}. This is not supported in basic serialization, either define a rule for this type or use serialization_mirrors
Stack Trace:
#0      Serialization.addRuleFor (package:serialization/serialization.dart:309:6)
#1      Serialization.rulesFor (package:serialization/serialization.dart:426:34)
#2      Writer._process (package:serialization/src/reader_writer.dart:109:48)
#3      Trace.traceAll (package:serialization/src/reader_writer.dart:536:47)
#4      Writer.write (package:serialization/src/reader_writer.dart:76:19)
#5      Serialization.write (package:serialization/serialization.dart:353:35)
```

Any suggestions?

**Comment by alan-knight** [comment]
Like the error says, there isn't a rule for Set and you're using the non-mirror version, so it can't just define one. It would not be unreasonable for the basic system to define a rule for Set.

To define your own, a reasonable one would be something like
class SetRule extends CustomRule {
  appliesTo(x) => x is Set;
  getState(x) => x.toList();
  create(state) => new Set();
  setState(obj, state) => obj.addAll(state);
}

**Comment by gazialankus** [comment]
This rule worked just fine, thank you. It's just that Maps and Lists working made me expect Sets to work as well. Thanks!
